# Generated by Django 4.1.2 on 2023-08-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("title", models.CharField(max_length=60)),
                ("description", models.TextField()),
                (
                    "todo_type",
                    models.CharField(
                        choices=[("1", "Urgent"), ("2", "Regular"), ("3", "Low")],
                        default="2",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
