# Generated by Django 4.1.2 on 2023-09-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.ManyToManyField(to="core.tag"),
        ),
    ]
